"""meeting closures: meeting_closures 표(회의록당 1행, 종료 구분·처리자·시각과 삭제 처리자·시각) 추가 (autogenerate).
기존 표·칸·데이터는 바꾸지 않는다(meetings 표를 다시 만들지 않도록 따로 둠). downgrade 는 행이 있으면 거부하고,
비어 있을 때만 표를 없앤다(수동 추가).

Revision ID: 0f82186010dc
Revises: 7c021789291d
Create Date: 2026-10-02 16:40:17.458614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f82186010dc'
down_revision: Union[str, Sequence[str], None] = '7c021789291d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_closures',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('end_kind', sa.String(length=20), nullable=True),
    sa.Column('ended_by', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("end_kind IS NULL OR end_kind IN ('auto', 'manager')", name=op.f('ck_meeting_closures_end_kind_valid')),
    sa.ForeignKeyConstraint(['deleted_by'], ['accounts.id'], name=op.f('fk_meeting_closures_deleted_by_accounts')),
    sa.ForeignKeyConstraint(['ended_by'], ['accounts.id'], name=op.f('fk_meeting_closures_ended_by_accounts')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_closures_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meeting_closures_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('meeting_id', name=op.f('pk_meeting_closures'))
    )
    with op.batch_alter_table('meeting_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_closures_deleted_by'), ['deleted_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_closures_ended_by'), ['ended_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_closures_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    rows = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM meeting_closures")).scalar_one()
    if rows:
        raise RuntimeError(f"downgrade 거부: 종료·삭제 기록 {rows}건이 있어 지우면 기록이 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 종료·삭제 기록이 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_closures_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_closures_ended_by'))
        batch_op.drop_index(batch_op.f('ix_meeting_closures_deleted_by'))

    op.drop_table('meeting_closures')
    # ### end Alembic commands ###
