"""transcripts and audio retention: transcripts 표 + tenants.audio_retention_days (autogenerate).
downgrade 는 데이터를 지우지 않는다: 전사문 행이나 보관 일수 값이 있으면 거부하고, 비어 있을 때만 표·열을 없앤다(수동 추가).

Revision ID: 2b93bc811d65
Revises: 54850384690d
Create Date: 2026-10-01 16:16:48.725794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b93bc811d65'
down_revision: Union[str, Sequence[str], None] = '54850384690d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('stt_provider', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_transcripts_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_transcripts_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts')),
    sa.UniqueConstraint('meeting_id', name=op.f('uq_transcripts_meeting_id'))
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_retention_days', sa.Integer(), nullable=True, comment='업로드 음성 보관 일수(NULL=무기한). 법무 검토 후 삭제 작업 추가 예정'))

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    conn = op.get_bind()
    transcripts = conn.execute(sa.text("SELECT COUNT(*) FROM transcripts")).scalar_one()
    retention = conn.execute(sa.text("SELECT COUNT(*) FROM tenants WHERE audio_retention_days IS NOT NULL")).scalar_one()
    if transcripts or retention:
        raise RuntimeError(
            f"downgrade 거부: 전사문 {transcripts}건·보관 일수 설정 {retention}건이 있어 지우면 데이터가 사라집니다. "
            "백업 후 사람이 직접 판단해 정리하세요."
        )


def downgrade() -> None:
    """Downgrade schema. 데이터가 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('audio_retention_days')

    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_tenant_id'))

    op.drop_table('transcripts')
    # ### end Alembic commands ###
