"""mail outbox: mail_outbox 표 (autogenerate).
downgrade 는 데이터를 지우지 않는다: 메일 기록이 있으면 거부하고, 비어 있을 때만 표를 없앤다(수동 추가).

Revision ID: 40b973d07351
Revises: a1cba09b5031
Create Date: 2026-10-01 16:48:58.351798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b973d07351'
down_revision: Union[str, Sequence[str], None] = 'a1cba09b5031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('immediate_new_minutes', 'daily_reminder')", name=op.f('ck_mail_outbox_kind_valid')),
    sa.CheckConstraint("status IN ('queued', 'sent', 'failed', 'skipped')", name=op.f('ck_mail_outbox_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_mail_outbox_account_id_accounts')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_mail_outbox_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_outbox')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_mail_outbox_dedupe_key'))
    )
    with op.batch_alter_table('mail_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_outbox_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mail_outbox_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    rows = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM mail_outbox")).scalar_one()
    if rows:
        raise RuntimeError(f"downgrade 거부: 메일 기록 {rows}건이 있어 지우면 데이터가 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 데이터가 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_outbox_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mail_outbox_account_id'))

    op.drop_table('mail_outbox')
    # ### end Alembic commands ###
