"""action item close and delete records: action_items 에 종결·삭제 기록 칸(closed_by·closed_at·deleted_by·deleted_at) 추가 (autogenerate).
기존 칸·데이터는 바꾸지 않는다(상태값 closed·deleted 는 이미 있음). downgrade 는 기록이 하나라도 있으면 거부하고,
모두 비어 있을 때만 칸을 없앤다(수동 추가).

Revision ID: 4ad1176618ed
Revises: dcdcca46db71
Create Date: 2026-10-02 15:39:13.529506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad1176618ed'
down_revision: Union[str, Sequence[str], None] = 'dcdcca46db71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_action_items_closed_by'), ['closed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_deleted_by'), ['deleted_by'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_action_items_closed_by_accounts'), 'accounts', ['closed_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_action_items_deleted_by_accounts'), 'accounts', ['deleted_by'], ['id'])

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    rows = op.get_bind().execute(sa.text(
        "SELECT COUNT(*) FROM action_items WHERE closed_by IS NOT NULL OR closed_at IS NOT NULL "
        "OR deleted_by IS NOT NULL OR deleted_at IS NOT NULL"
    )).scalar_one()
    if rows:
        raise RuntimeError(f"downgrade 거부: 종결·삭제 기록이 있는 업무 {rows}건이 있어 지우면 기록이 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 종결·삭제 기록이 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_action_items_deleted_by_accounts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_action_items_closed_by_accounts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_action_items_deleted_by'))
        batch_op.drop_index(batch_op.f('ix_action_items_closed_by'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('closed_by')

    # ### end Alembic commands ###
