"""jobs and meeting statuses: jobs 표 추가(autogenerate) + meetings.status CHECK 에 failed·no_content 추가(수동: autogenerate 는 CHECK 변경을 감지하지 않음)

Revision ID: 54850384690d
Revises: bf1bfa11e676
Create Date: 2026-10-01 16:07:51.114875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_OLD_MEETING_STATUS = "status IN ('processing', 'awaiting_confirmation', 'confirmed')"
_NEW_MEETING_STATUS = "status IN ('processing', 'awaiting_confirmation', 'confirmed', 'failed', 'no_content')"


def _replace_meeting_status_check(expr: str) -> None:
    # SQLite 는 CHECK 를 바로 바꿀 수 없어 batch(표 재생성)로, 다른 엔진은 DROP/ADD CONSTRAINT 로 처리된다
    with op.batch_alter_table("meetings", schema=None) as batch_op:
        batch_op.drop_constraint(op.f("ck_meetings_status_valid"), type_="check")
        batch_op.create_check_constraint(op.f("ck_meetings_status_valid"), expr)


# revision identifiers, used by Alembic.
revision: str = '54850384690d'
down_revision: Union[str, Sequence[str], None] = 'bf1bfa11e676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed', 'no_content')", name=op.f('ck_jobs_status_valid')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_jobs_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_jobs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
    _replace_meeting_status_check(_NEW_MEETING_STATUS)


def downgrade() -> None:
    """Downgrade schema. failed·no_content 상태인 회의록이 있으면 CHECK 복원이 실패한다(데이터를 지우지 않음)."""
    _replace_meeting_status_check(_OLD_MEETING_STATUS)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_meeting_id'))

    op.drop_table('jobs')
    # ### end Alembic commands ###
