"""meeting holds: meeting_holds 표(회의록당 1행, 보류 표시와 마지막 보류·재개 기록) 추가 (autogenerate).
기존 표·칸·데이터는 바꾸지 않는다(meetings 표를 다시 만들지 않도록 따로 둠). downgrade 는 행이 있으면 거부하고,
비어 있을 때만 표를 없앤다(수동 추가).

Revision ID: 7c021789291d
Revises: 4ad1176618ed
Create Date: 2026-10-02 16:08:50.267764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c021789291d'
down_revision: Union[str, Sequence[str], None] = '4ad1176618ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_holds',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('on_hold', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('on_hold_by', sa.Integer(), nullable=True),
    sa.Column('on_hold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_by', sa.Integer(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_holds_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['on_hold_by'], ['accounts.id'], name=op.f('fk_meeting_holds_on_hold_by_accounts')),
    sa.ForeignKeyConstraint(['resumed_by'], ['accounts.id'], name=op.f('fk_meeting_holds_resumed_by_accounts')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meeting_holds_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('meeting_id', name=op.f('pk_meeting_holds'))
    )
    with op.batch_alter_table('meeting_holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_holds_on_hold_by'), ['on_hold_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_holds_resumed_by'), ['resumed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_holds_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    rows = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM meeting_holds")).scalar_one()
    if rows:
        raise RuntimeError(f"downgrade 거부: 보류·재개 기록 {rows}건이 있어 지우면 기록이 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 보류·재개 기록이 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_holds_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_holds_resumed_by'))
        batch_op.drop_index(batch_op.f('ix_meeting_holds_on_hold_by'))

    op.drop_table('meeting_holds')
    # ### end Alembic commands ###
