"""meeting views and notices: meeting_views·notices 표 (autogenerate).
downgrade 는 데이터를 지우지 않는다: 열람 기록이나 안내가 있으면 거부하고, 비어 있을 때만 표를 없앤다(수동 추가).

Revision ID: a1cba09b5031
Revises: 2b93bc811d65
Create Date: 2026-10-01 16:39:48.874468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1cba09b5031'
down_revision: Union[str, Sequence[str], None] = '2b93bc811d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_views',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('first_viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_meeting_views_account_id_accounts')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_views_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meeting_views_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('meeting_id', 'account_id', name=op.f('pk_meeting_views'))
    )
    with op.batch_alter_table('meeting_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_views_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_views_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("entity_type IN ('meeting', 'action_item')", name=op.f('ck_notices_entity_type_valid')),
    sa.CheckConstraint("kind IN ('confirmed_notice')", name=op.f('ck_notices_kind_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_notices_account_id_accounts')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_notices_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notices_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notices'))
    )
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notices_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notices_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    conn = op.get_bind()
    views = conn.execute(sa.text("SELECT COUNT(*) FROM meeting_views")).scalar_one()
    notices = conn.execute(sa.text("SELECT COUNT(*) FROM notices")).scalar_one()
    if views or notices:
        raise RuntimeError(
            f"downgrade 거부: 열람 기록 {views}건·안내 {notices}건이 있어 지우면 데이터가 사라집니다. "
            "백업 후 사람이 직접 판단해 정리하세요."
        )


def downgrade() -> None:
    """Downgrade schema. 데이터가 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_notices_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_notices_account_id'))

    op.drop_table('notices')
    with op.batch_alter_table('meeting_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_views_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_views_account_id'))

    op.drop_table('meeting_views')
    # ### end Alembic commands ###
