"""core tables: v2 핵심 테이블 7개 (autogenerate, Boolean 기본값만 엔진 중립 sa.true()/sa.false()로 수정)

Revision ID: bf1bfa11e676
Revises: 
Create Date: 2026-10-01 15:40:41.829665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf1bfa11e676'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('auto_confirm_days', sa.Integer(), server_default='5', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('name', name=op.f('uq_tenants_name'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('login_id', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("rank IN ('staff', 'manager', 'executive')", name=op.f('ck_accounts_rank_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_accounts_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('login_id', name=op.f('uq_accounts_login_id'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_account_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_account_id'], ['accounts.id'], name=op.f('fk_events_actor_account_id_accounts')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_actor_account_id'), ['actor_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("origin IN ('audio_minutes', 'uploaded')", name=op.f('ck_source_documents_origin_valid')),
    sa.ForeignKeyConstraint(['registered_by'], ['accounts.id'], name=op.f('fk_source_documents_registered_by_accounts')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_source_documents_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents'))
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_registered_by'), ['registered_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decisions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirm_kind', sa.String(length=20), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_confirm_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confirm_kind IS NULL OR confirm_kind IN ('manager', 'registration', 'period_elapsed', 'due_reached')", name=op.f('ck_meetings_confirm_kind_valid')),
    sa.CheckConstraint("status IN ('processing', 'awaiting_confirmation', 'confirmed')", name=op.f('ck_meetings_status_valid')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['accounts.id'], name=op.f('fk_meetings_confirmed_by_accounts')),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], name=op.f('fk_meetings_source_document_id_source_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meetings_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetings'))
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_confirmed_by'), ['confirmed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_source_document_id'), ['source_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('due_undetermined', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirm_kind', sa.String(length=20), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_start_sec', sa.Float(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('extract_model', sa.String(length=100), server_default='', nullable=False),
    sa.Column('prompt_version', sa.String(length=50), server_default='', nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confirm_kind IS NULL OR confirm_kind IN ('manager', 'registration', 'period_elapsed', 'due_reached')", name=op.f('ck_action_items_confirm_kind_valid')),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'closed', 'deleted')", name=op.f('ck_action_items_status_valid')),
    sa.ForeignKeyConstraint(['assignee_id'], ['accounts.id'], name=op.f('fk_action_items_assignee_id_accounts')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['accounts.id'], name=op.f('fk_action_items_confirmed_by_accounts')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_action_items_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_action_items_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_items'))
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_items_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_confirmed_by'), ['confirmed_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_meeting_participants_account_id_accounts')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_participants_meeting_id_meetings')),
    sa.PrimaryKeyConstraint('meeting_id', 'account_id', name=op.f('pk_meeting_participants'))
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_participants_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_participants_account_id'))

    op.drop_table('meeting_participants')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_confirmed_by'))
        batch_op.drop_index(batch_op.f('ix_action_items_assignee_id'))

    op.drop_table('action_items')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_meetings_confirmed_by'))

    op.drop_table('meetings')
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_source_documents_registered_by'))

    op.drop_table('source_documents')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_events_actor_account_id'))

    op.drop_table('events')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_tenant_id'))

    op.drop_table('accounts')
    op.drop_table('tenants')
    # ### end Alembic commands ###
