"""org and projects: departments·account_departments·projects·project_members 표 추가.
기존 표·칸·데이터는 바꾸지 않는다(meetings 표를 다시 만들지 않도록 모두 별도 표). downgrade 는 행이 있으면 거부하고, 모두 비어 있을 때만 표를 없앤다.

Revision ID: c7e2a91d4b30
Revises: b4d8f2a6c901
Create Date: 2026-10-07 11:19:40.657795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e2a91d4b30'
down_revision: Union[str, Sequence[str], None] = 'b4d8f2a6c901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('normal', 'executive')", name=op.f('ck_departments_kind_valid')),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], name=op.f('fk_departments_parent_id_departments')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_departments_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_departments_tenant_name')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('account_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('head', 'member')", name=op.f('ck_account_departments_role_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_account_departments_account_id_accounts')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_account_departments_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_departments')),
    sa.UniqueConstraint('account_id', 'department_id', name='uq_account_departments_account_department')
    )
    with op.batch_alter_table('account_departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_departments_department_id'), ['department_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registered_by', sa.Integer(), nullable=False),
    sa.Column('lead_account_id', sa.Integer(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending_approval', 'active', 'rejected')", name=op.f('ck_projects_status_valid')),
    sa.ForeignKeyConstraint(['decided_by'], ['accounts.id'], name=op.f('fk_projects_decided_by_accounts')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_projects_department_id_departments')),
    sa.ForeignKeyConstraint(['lead_account_id'], ['accounts.id'], name=op.f('fk_projects_lead_account_id_accounts')),
    sa.ForeignKeyConstraint(['registered_by'], ['accounts.id'], name=op.f('fk_projects_registered_by_accounts')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_lead_account_id'), ['lead_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_registered_by'), ['registered_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('lead', 'manager', 'member')", name=op.f('ck_project_members_role_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_project_members_account_id_accounts')),
    sa.ForeignKeyConstraint(['added_by'], ['accounts.id'], name=op.f('fk_project_members_added_by_accounts')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'account_id', name='uq_project_members_project_account')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


_TABLES = ("project_members", "projects", "account_departments", "departments")


def _refuse_if_data_exists() -> None:
    conn = op.get_bind()
    counts = {name: conn.execute(sa.text(f"SELECT COUNT(*) FROM {name}")).scalar_one() for name in _TABLES}
    if any(counts.values()):
        found = ", ".join(f"{name} {n}건" for name, n in counts.items() if n)
        raise RuntimeError(f"downgrade 거부: 조직·프로젝트 기록({found})이 있어 지우면 기록이 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 기록이 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_account_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_projects_registered_by'))
        batch_op.drop_index(batch_op.f('ix_projects_lead_account_id'))
        batch_op.drop_index(batch_op.f('ix_projects_department_id'))

    op.drop_table('projects')
    with op.batch_alter_table('account_departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_departments_department_id'))

    op.drop_table('account_departments')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_departments_parent_id'))

    op.drop_table('departments')
    # ### end Alembic commands ###
