"""meeting classifications: meeting_classifications 표(회의 유형 5종·프로젝트 소속) 추가.
기존 표·칸·데이터는 바꾸지 않는다(meetings 표를 다시 만들지 않도록 따로 둠). downgrade 는 행이 있으면 거부하고, 비어 있을 때만 표를 없앤다.

Revision ID: d3a8f15c7e92
Revises: c7e2a91d4b30
Create Date: 2026-10-07 11:45:49.483481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a8f15c7e92'
down_revision: Union[str, Sequence[str], None] = 'c7e2a91d4b30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("meeting_type IN ('regular', 'irregular', 'project', 'external', 'other')", name=op.f('ck_meeting_classifications_meeting_type_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], name=op.f('fk_meeting_classifications_created_by_accounts')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_classifications_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_meeting_classifications_project_id_projects')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meeting_classifications_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_classifications')),
    sa.UniqueConstraint('meeting_id', name=op.f('uq_meeting_classifications_meeting_id'))
    )
    with op.batch_alter_table('meeting_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_classifications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_classifications_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    rows = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM meeting_classifications")).scalar_one()
    if rows:
        raise RuntimeError(f"downgrade 거부: 회의 유형·프로젝트 연결 기록 {rows}건이 있어 지우면 기록이 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 기록이 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_classifications_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_classifications_project_id'))

    op.drop_table('meeting_classifications')
    # ### end Alembic commands ###
