"""meeting speakers: meeting_speakers 표(화자 표기 → 계정 또는 미등록 이름) (autogenerate).
downgrade 는 데이터를 지우지 않는다: 매핑이 있으면 거부하고, 비어 있을 때만 표를 없앤다(수동 추가).

Revision ID: dcdcca46db71
Revises: 40b973d07351
Create Date: 2026-10-02 11:12:43.917760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcdcca46db71'
down_revision: Union[str, Sequence[str], None] = '40b973d07351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_speakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(account_id IS NOT NULL AND display_name = '') OR (account_id IS NULL AND display_name <> '')", name=op.f('ck_meeting_speakers_account_or_name')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_meeting_speakers_account_id_accounts')),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_speakers_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_meeting_speakers_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['updated_by'], ['accounts.id'], name=op.f('fk_meeting_speakers_updated_by_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_speakers')),
    sa.UniqueConstraint('meeting_id', 'label', name='uq_meeting_speakers_meeting_label')
    )
    with op.batch_alter_table('meeting_speakers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_speakers_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_speakers_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_speakers_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    rows = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM meeting_speakers")).scalar_one()
    if rows:
        raise RuntimeError(f"downgrade 거부: 화자 매핑 {rows}건이 있어 지우면 데이터가 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 데이터가 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_speakers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_speakers_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_speakers_meeting_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_speakers_account_id'))

    op.drop_table('meeting_speakers')
    # ### end Alembic commands ###
