"""item supersessions: item_supersessions 표(업무 대체 연결) 추가.
기존 표·칸·데이터는 바꾸지 않는다(action_items 표를 다시 만들지 않도록 따로 둠). downgrade 는 행이 있으면 거부하고, 비어 있을 때만 표를 없앤다.

Revision ID: e5b1c7d29a64
Revises: d3a8f15c7e92
Create Date: 2026-10-07 12:56:08.469024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b1c7d29a64'
down_revision: Union[str, Sequence[str], None] = 'd3a8f15c7e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_supersessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('old_item_id', sa.Integer(), nullable=False),
    sa.Column('new_item_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('old_item_id <> new_item_id', name=op.f('ck_item_supersessions_old_new_differ')),
    sa.ForeignKeyConstraint(['new_item_id'], ['action_items.id'], name=op.f('fk_item_supersessions_new_item_id_action_items')),
    sa.ForeignKeyConstraint(['old_item_id'], ['action_items.id'], name=op.f('fk_item_supersessions_old_item_id_action_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_item_supersessions_project_id_projects')),
    sa.ForeignKeyConstraint(['source_request_id'], ['events.id'], name=op.f('fk_item_supersessions_source_request_id_events')),
    sa.ForeignKeyConstraint(['superseded_by'], ['accounts.id'], name=op.f('fk_item_supersessions_superseded_by_accounts')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_item_supersessions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_supersessions')),
    sa.UniqueConstraint('old_item_id', name=op.f('uq_item_supersessions_old_item_id'))
    )
    with op.batch_alter_table('item_supersessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_supersessions_new_item_id'), ['new_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_supersessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_supersessions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def _refuse_if_data_exists() -> None:
    rows = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM item_supersessions")).scalar_one()
    if rows:
        raise RuntimeError(f"downgrade 거부: 업무 대체 기록 {rows}건이 있어 지우면 기록이 사라집니다. 백업 후 사람이 직접 판단해 정리하세요.")


def downgrade() -> None:
    """Downgrade schema. 기록이 있으면 거부(데이터 삭제 없음)."""
    _refuse_if_data_exists()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_supersessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_supersessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_item_supersessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_item_supersessions_new_item_id'))

    op.drop_table('item_supersessions')
    # ### end Alembic commands ###
